cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('cart-summary/', views.cart_summary, name='cart_summary'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('adminsite/', admin.site.urls),
    path('', include('dxd.urls', namespace='dxd')),
    path('order/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('payment/', include('payments.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons'))
]

if settings.DEBUG: 
        urlpatterns += static(settings.MEDIA_URL, 
                              document_root=settings.MEDIA_ROOT)

coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

dxd/urls.py
from django.urls import path
from . import views

app_name = 'dxd'

urlpatterns = [
    path('', views.home, name='home'),
    path('about-us/', views.about_us, name='about-us'),
    path('contact-us/', views.contact_us, name='contact-us'),
    path('track-order/', views.track_order, name='track-order'),
    path('corporate-responsibility/', views.corporate_responsibility, name='corporate-responsibility'),
    path('investor-site/', views.investor_site, name='investor-site'),
    path('careers/', views.career_page, name='careers'),
    path('black-friday/', views.black_friday, name='black-friday'),
    path('new-arrival/', views.new_arrival, name='new-arrival'),
    path('best-seller/', views.best_sellers, name='best-seller'),
    path('mobile-apps/', views.mobile_apps, name='mobile-apps'),
    path('coupons/', views.gift_vouchers, name='coupons'),
    path('summer/', views.summer, name='summer'),
    path('gifts/', views.gifts, name='gifts'),
    path('help/', views.help, name='help'),
    path('travels/', views.travels, name='travels'),
    path('terms-conditions/', views.terms_condition, name='terms-conditions'),
    path('delivery-returns/', views.delivery_returns, name='delivery-returns'),
    path('search/', views.search, name='search'),
    path('product/<slug:slug>/', views.product, name='product'),
    path('category/<slug:category_slug>/', views.category_list, name='products_list_by_category'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('success/', views.success, name='success'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf')
]

templates/pages/best_seller.html
{% extends "pages/base.html" %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/shopping.css' %}">
    <!-- CSS SWEET ALERT LINK -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.css">


        <!--********************** HERO SECTION   *************************** -->

        <div id="content-d" class="category">
            <nav class="sub_category">
                <ul>
                    <!-- <li class="">
                        <a class="fashion_category" data-rel="#content-e" href="/sub_category/women.html">WOMEN</a>
                    </li> -->

                    <li>
                        <h5 href="">
                            25% OFF EVERYTHING!* <br>
                            <span>With code: WOO25</span>
                            </h6>
                    </li>
                    <!-- <li>
                        <a class="fashion_category" data-rel="#content-f" href="/sub_category/men.html">MEN</a>
                    </li> -->
                </ul>
            </nav>

            <section class="p-2">
                <div class="position-relative">

                    <section>
                        <div class="d-flex justify-content-between pt-3 pb-2 filters_container bg-white">
                            <div class="d-flex place-items-center pb-3 pl-3">
                                <div class="select_filters pl-3">
        
                                    <div class="d-flex justify-content-center align-items-center mr-2">
        
                                        <div class="dropdown">
                                        </div>
        
        
                                    </div>
                                    <div class="d-flex justify-content-center align-items-center mr-2">
        
                                        <div class="dropdown">
                                        </div>
        
        
                                    </div>
                                    <div class="d-flex justify-content-center align-items-center mr-2">
        
                                        <div class="dropdown">
                                        </div>
        
        
                                    </div>
                                    <div class="d-flex justify-content-center align-items-center mr-2">
        
                                        <div class="dropdown">
                                        </div>
        
        
                                    </div>
                                    <div class="d-flex justify-content-center align-items-center mr-2">
        
                                        <div class="dropdown">
                                        </div>
        
        
                                    </div>
                                    <!-- <select name="" id="" class="border py-2 px-3">
                                        <option value="">Size</option>
                                    </select>
                                    <select name="" id="" class="border py-2 px-3">
                                        <option value="">Style</option>
                                    </select>
                                    <select name="" id="" class="border py-2 px-3">
                                        <option value="">Color</option>
                                    </select>
                                    <select name="" id="" class="border py-2 px-3">
                                        <option value="">Price</option>
                                    </select> -->
                                </div>
                            </div>
        
                            
        
                            <!-- <div class="pr-3">
                                <div class="d-flex justify-content-center align-items-center">
        
                                    <div class="dropdown">
                                        <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                                            aria-expanded="false">
                                            <span>Sort By</span>
                                            <i class="fa fa-caret-down"></i>
                                        </button>
                                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                            <option value="">Sort By</option>
                                            <option value="price_asc" {% if current_sorting == 'price_asc' %}selected{% endif %}>Price (low to high)</option>
                                            <option value="price_desc" {% if current_sorting == 'price_desc' %}selected{% endif %}>Price (high to low)</option>
                                            <option value="rating_asc" {% if current_sorting == 'rating_asc' %}selected{% endif %}>Rating (low to high)</option>
                                            <option value="rating_desc" {% if current_sorting == 'rating_desc' %}selected{% endif %}>Rating (high to low)</option>
                                            <option value="name_asc" {% if current_sorting == 'name_asc' %}selected{% endif %}>Name (A-Z)</option>
                                            <option value="name_desc" {% if current_sorting == 'name_desc' %}selected{% endif %}>Name (Z-A)</option>
                                            <option value="category_asc" {% if current_sorting == 'category_asc' %}selected{% endif %}>Category (A-Z)</option>
                                            <option value="category_desc" {% if current_sorting == 'category_desc' %}selected{% endif %}>Category (Z-A)</option>
                                        </ul>
                                    </div>
                
                
                                </div>
                             
                            </div> -->
                        </div>
                        <hr>
                        <div class="might_like_container">
                            <div class="d-flex justify-content-between px-2 pb-3">
                                <h5 class="font-weight-bold">Best Sellers</h5>
                                <div class="pr-2">
                            </div>
                        </div>

                            <!--********************************************************************************************-->
                            <!--********************** ADDED CAROUSEL TO ALL THE IMAGES IN THIS SECTION ***************************-->
                            <!--*******************************************************************************************-->
                            <ul class="">
                                <li class="">
                                    <div class="might_like_sub-container">
                                        {% for product in best_seller %}
                                        <div id="myCarousel" class="carousel slide">
                                            <!-- Wrapper for carousel items -->
                                            <div class="carousel-inner">
                                                <!-- <div class="carousel-item active"> -->
                                                    <a href="{{product.get_absolute_url}}">
                                                        <img class="image1" src="{{product.photo_main.url}}" alt="">
                                                    </a>
                                                </div>
        
                                                <!-- <div class="carousel-item bg-dark">
                                                    <img src="/images/sneakers1.PNG" alt="Second Slide">
                                                </div>
        
                                                <div class="carousel-item">
                                                    <img src="/images/sneakers1.PNG" alt="Third Slide">
                                                </div> -->
        
                                            <!-- Carousel controls -->
                                            <a class="carousel-control-prev" href="#myCarousel" data-slide="prev">
                                                <span class="carousel-control-prev-icon"></span>
                                            </a>
                                            <a class="carousel-control-next" href="#myCarousel" data-slide="next">
                                                <span class="carousel-control-next-icon"></span>
                                            </a>
                                            <div class="might_like_details">
                                                
                                                <div class="d-flex justify-content-between w-100">
                                                    <a class="text-decoration-none text-dark font-weight-bold" ref="{{product.get_absolute_url}}"><p class="product_name">{{product.name}}</p></a>
                                                    
                                                </div>
                                                <small class="text-dark text-muted d-block">{{product.description}}</small>
                                                <h6 class=" font-weight-bold pb-0">N{{product.price}}</h6>
                                            </div>
                                        </div>
    
                                        <!-- <div class="leg_wear"> <img src="/images/leg-wear.jpg" alt=""></div> -->
                                        <!-- <div class="might_like_details">
                                            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                            {% csrf_token %}
                                            <button type="submit" class="add_to_bag"><a>Add to Cart</a></button>
                                            </form>
                                            <div class="d-flex justify-content-between w-100">
                                                <a href="{{product.get_absolute_url}}"><h6>{{product.name}}</h6></a>
                                                <p class=" font-weight-bold pb-0">N {{product.price}}</p>
                                            </div>
                                            <small class="text-danger d-block">{{product.description}}</small>
                                        </div> -->
                                        {% empty %}
                                        <h5 class="text-center">No Product listed yet, Please check back later thanks.</h5>
                                        {% endfor %}
                                    </div>
                                </li>
                            </ul>
                             <!--********************************************************************************************-->
                            <!--***************ADDED CAROUSEL TO ALL THE IMAGES IN THIS SECTION ENDS HERE ***************************-->
                            <!--*******************************************************************************************-->

                        </div>

                    </section>



                </div>
                <script src="{% static 'js/shopping.js' %}"></script>

{% endblock %}

templates/pages/checkout.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <title>Order Page</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <!-- Css link -->
  <!-- <link rel="stylesheet" href="/css/style.css"> -->
  <link rel="stylesheet" href="{% static 'css/checkout.css' %}">
  <link rel="shortcut icon" href="{% static 'images/DXD_synergy_logo.jpg' %}" type="image/x-icon">

  <!-- <link rel="stylesheet" href="/css/myAccount.css"> -->
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
  <main>
    {% with total_items=cart|length %}
    {% if total_items > 0 %}
    <nav>
      <div class="synergy_logo">
        <a href="{% url 'dxd:home' %}">
          <img src="{% static 'images/DXD_synergy_logo.jpg' %}" alt="">
        </a>
      </div>
      <div class="checkout">
        <h3 class="">Order Confirmation Page</h3>
      </div>
    </nav>
    
    <section class="row section justify-content-center">

      <div class="col-md-6 col-lg-6 delivery_content">
       
        <div>
          <form class="bg-white px-5 py-4" action="{% url 'orders:order_create' %}" method="POST">
            {% csrf_token %}
            <div class="sign_up_with mb-4">
              <h4 class="mb-3">DELIVERY INFORMATION</h4>
            </div>
            <div class="form-group mb-3">
              <label for="exampleInputEmail1" class="font-weight-bold text-muted">FIRST NAME:</label>
              <input type="text" name="first_name" class="form-control w-md-75" id="exampleInputEmail1" aria-describedby="emailHelp"
                placeholder="" required>
            </div>
  
            <div class="form-group mb-3">
              <label for="exampleInputEmail1" class="font-weight-bold text-muted">LAST NAME:</label>
              <input type="text" name="last_name" class="form-control w-md-75" id="exampleInputEmail1" aria-describedby="emailHelp"
                placeholder="" required>
            </div>
  
            <div class="form-group mb-3">
              <label for="exampleInputEmail1" class="font-weight-bold d-md-flex text-muted">MOBILE:<small id="emailHelp"
                  class="form-text text-muted pl-md-3">(For delivery
                  updates ):</small> </label>
              <input type="number" name="phone" class="form-control w-md-75" id="exampleInputEmail1" aria-describedby="emailHelp"
                placeholder="" required>
            </div>

            <div class="form-group mb-3">
              <label for="exampleInputEmail1" class="font-weight-bold text-muted">E-MAIL:</label>
              <input type="email" name="email" class="form-control w-md-75" id="exampleInputEmail1" aria-describedby="emailHelp"
                placeholder="" required>
            </div>
  
            <div class="form-group mb-3">
              <label for="exampleInputEmail1" class="font-weight-bold text-muted">ADDRESS:</label>
              <input type="text" name="address" class="form-control w-md-75 mb-2" id="exampleInputEmail1" aria-describedby="emailHelp"
                placeholder="" required>
            </div>
  
            <div class="form-group mb-3">
              <label for="exampleInputEmail1" class="font-weight-bold text-muted">STATE:</label>
              <input type="text" name="state" class="form-control w-md-75" id="exampleInputEmail1" aria-describedby="emailHelp"
                placeholder="" required>
            </div>

            <div class="form-group">
              <label for="exampleInputEmail1" class="font-weight-bold text-muted">POSTCODE:</label>
              <input type="number" name="postal_code" class="form-control w-md-50" id="exampleInputEmail1" aria-describedby="emailHelp"
                placeholder="" required>
            </div>
  
            <div class="form-group">
              <label for="exampleInputEmail1" class="font-weight-bold text-muted">COUNTRY</label>
              <input type="text" name="country" class="form-control w-md-75" id="exampleInputEmail1" aria-describedby="emailHelp"
                placeholder="" required>
            </div>

            <label for="payments">Choose a Payment Option:</label>

              <select name="payment_option" id="payments">
                <option value="pay_on_delivery">Pay on delivery</option>
                <option value="paystack" selected>Paystack</option>
              </select>
  
  
              <div class="form-group pt-3">
                <button class="start_shopping_button btn btn-success" type="submit"><a>PLACE ORDER</a></button>
  
              </div>
  
              <h5 class="we_accept mt-3">WE ACCEPT:</h5>
              <div class="icons_and_images">
  
                <ul class="electronic_images d-flex">
                  <li class="checkout_visa"><img src="https://images.asos-media.com/navigation/visa-png" alt="">
                  </li>
                  <li class="checkout_mastercard"><img src="https://images.asos-media.com/navigation/mastercard-png"
                      alt="">
                  </li>
                  <!-- <li class="checkout_pay-pal"><img src="https://images.asos-media.com/navigation/pay-pal-png" alt="">
                  </li> -->
                  <li class="checkout_american-express"><img
                      src="https://images.asos-media.com/navigation/american-express-png" alt=""></li>
                  <li class="visa-electron_image2"><img src="https://images.asos-media.com/navigation/visa-electron-png"
                      alt=""></li>
                </ul>
              </div>
  
            </div>
  
          </form>
  
          <div class="w-75 mt-3 ">
            <p class="text-muted privacy_policy">
              By placing your order you agree to our <a href="{% url 'dxd:terms-conditions' %}">Terms and condition,</a><a href="{% url 'dxd:terms-conditions' %}"> Privacy</a> and
              <a href="{% url 'dxd:delivery-returns' %}">returns Policy.</a> You also consent
              to some of your data being stored by SYNERGY, which may be used to make future shopping experiences better
              for you.
            </p>
          </div>
  
        </div>
  
      </div>

      <div class="col-lg-4 col-md-6 description_content bg-white p-2">
        <div class="d-flex mb-0 justify-content-between mb-2 bg-white p-2">
          <h5>MY CART</h5>
          <p class="mb-0">Please confirm your items in cart!</p>
        </div>
        <hr class="mt-0">
        {% for item in cart %}
        {% with product=item.product %}
        <div class="mb-2 bg-white pl-2 pr-0">
          <div class="d-flex justify-content-between">
            <div class="w-100">
              <div class="d-flex bag_details">
                <a href="{{product.get_absolute_url}}"><div class="myBag_image mt-1"><img src="{{ product.photo_main.url }}" alt=""></div></a>
                <div class="w-100">
                  <h5><a class="text-decoration-none text-dark" href="{{product.get_absolute_url}}">{{ product.name }}</a></h5>
                  <p class="mb-0 text-muted">N{{ product.price|floatformat:2 }}</p>
                  <div class="d-flex justify-content-between mt-2">
                    <p class="pr-2"> Quantity: {{ item.quantity }}</p>
                    <p class="pr-2"> Colour: {{ product.color }}</p>
                   
                  </div>
                 
                </div>
                <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                  <div>
                    {% csrf_token %}
                    <button class="border border-none mr-1 mt-1"><a class="bg-white px-1 py-0 text-danger" type="submit">X</a></button>
                    <!-- <i type="submit" class="fa fa-times pr-1" aria-hidden="true"></i> -->
                  </div>
                </form>
              </div>
<hr>
              {% endwith %}
              {% endfor %}
              
            </div>
          </div>
        </div>
        {% if cart.coupon %}
        <div class="d-flex justify-content-end sub_total mb-2 bg-white py-3 px-5">
          <br>
          <br>
          "{{ cart.coupon.code }}" offers ({{ cart.coupon.discount }}% off)
          <h5 class="pr-1">TOTAL</h5>
          <h5>N{{ cart.get_total_price_after_discount|floatformat:2  }}</h5>
        </div>
        {% else %}
        <div class="d-flex justify-content-end sub_total mb-2 bg-white py-3 px-5">
          <h5 class="pr-1">TOTAL</h5>
          <h5>N{{ cart.get_total_price|floatformat:2 }}</h5>
        </div>
        <a href="{% url 'dxd:home' %}">
          <input class="bg-info rounded border-0 text-white px-2 py-1" type="submit" value="Continue Shopping">
        </a>
        <br>
        <br>
        {% endif %}
        <p>Apply a coupon:</p>
      <form action="{% url 'coupons:apply' %}" method="post">
      {{ coupon_apply_form }}
      <input class="bg-info rounded border-0 text-white px-2 py-1" type="submit" value="Apply">
      {% csrf_token %}
      </form>

      </div>

    </section>
    {% else %}
      <!-- <div class="container text-justify">
        <div class="synergy_logo pb-5">
          <a href="{% url 'dxd:home' %}">
            <img src="{% static 'images/DXD_synergy_logo.jpg' %}" alt="">
          </a>
        </div>
        <div>
          <h3>Cart is empty.</h3>
          <p>You have not added any item to cart.</p>
        </div>
      </div> -->
      <div class="container h-100">
        <div class="row align-items-center h-100">
            <div class="col-6 mx-auto">
                <div class="card h-100 border-primary justify-content-center">
                    <div class="pl-3">
                      <div class="card-body text-center">
                        <h5 class="card-title">Empty Cart!</h5>
                        <p class="card-text">Please add item(s) into cart</p>
                        <a href="{% url 'dxd:home' %}" class="btn btn-primary">Continue shopping</a>
                      </div>
                    </div>
                </div>
            </div>
        </div>
      </div>
    {% endif %}
    {% endwith %}
   

  </main>














  <!-- <script>
    function toggle(source) {
      checkboxes = document.getElementsByName('foo');
      for (var checkbox in checkboxes)
        checkbox.checked = source.checked;
    }

    function toggle(source) {
      checkboxes = document.getElementsByName('foo');
      for (var i = 0, n = checkboxes.length; i < n; i++) {
        checkboxes[i].checked = source.checked;
      }
    }
  </script> -->




  <script src="{% static 'js/main.js' %}"></script>
  <script src="{% static 'js/checkout.js' %}"></script>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
</body>

</html>

templates/pages/delivery.html
{% extends "pages/base.html"%}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/delivery.css' %}">
    <main class="aabout-us">
        <section>
            <header>
                <div class="m-auto">
                    <a href="{% url 'dxd:home' %}"><img src="{% static 'images/DXD_synergy_logo.jpg' %}" alt=""></a>
                </div>
                <h3 class="mt-3">DELIVERY AND RETURNS</h3>
                <p>See below for information about the delivery & returns options in your country</p>
            </header>

            <div>
                <div class="  bg-white mb-3">
                    <div class="d-flex  justify-content-between m-auto sub_delivery_content">
                        <div class="w-100 border-right border-bottom text-center">
                            <button class="py-2 delivery active"
                                data-rel="#content-m">DELIVERY</button>
                        </div>
                        <div class="w-100 text-center border-bottom delivery_border">
                            <button class="py-2 delivery" data-rel="#content-n">RETURNS</button>
                        </div>
                    </div>
                </div>

                <div class="delivery_container" id="content-m">
                    <div class="d-flex justify-content-between bg-white p-3 mb-3">
                    </div>

                    <div class="d-flex justify-content-between place-items-center p-3 bg-white">
                        <div>
                            <i class="fa fa-truck fa-2x" aria-hidden="true"></i>
                            <h6>Standard Delivery</h6>
                            <h5>N5000.00</h5>
                            <b>Pay on Delivery -<span class="text-muted"> Lagos & Abuja</span></b> <br>
                        </div>
                        <div>
                            <!-- <i class="fa fa-angle-up fa-2x" aria-hidden="true"></i> -->
                        </div>
                    </div>

                    <div class="delivery_date">
                        <div class="px-4 py-3">
                            <p class="mb-0">Deliver</p>
                            <small>Note: Items are shipped immediately after order placement. </small>
                        </div>
                        <div class="d-flex py-4 pl-3 mb-3">
                            <i class="fa fa-question-circle-o font font-weight-bold" aria-hidden="true"></i>
                            <div class="more_info pl-3">
                                <h6>NEED MORE INFORMATION?</h6>
                                <div>See our <a href="{% url 'dxd:terms-conditions' %}">delivery FAG <div><img src="{% static 'images/clone-icon.png' %}" alt="">
                                        </div></a></div>
                            </div>
                        </div>
                    </div>


                </div>


                <div class="delivery_container" id="content-n">
                    <div class="d-flex justify-content-between bg-white p-3 mb-3">
                        <!-- <div class="flag"><img src="/images/nigerian_flag.png" alt=""></div>
                        <button>CHANGE</button> -->
                    </div>
                    <!-- <i class="fa fa-arrow-up" aria-hidden="true"></i> -->
                    <div class="d-flex justify-content-between place-items-center p-3 bg-white">
                        <div>

                            <div class=""><img src="{% static 'images/post-office-icon.png' %}" alt=""></div>
                            <h6 class="text-muted">Local Post Office</h6>
                            <h6>Local postage rates</h6>
                        </div>
                        <div>
                            <!-- <i class="fa fa-angle-up fa-2x" aria-hidden="true"></i> -->
                        </div>
                    </div>

                    <div class="delivery_date">
                        <div class="px-4 py-3">
                            <ul class="pl-3">
                                <li class="mb-0">Return through your local post office</li>
                                <li class="mb-0">You find a label on your parcel</li>
                            </ul>
                        </div>
                       
                        <div class="d-flex py-4 pl-3 more_info_container2">
                            <i class="fa fa-question-circle-o font font-weight-bold" aria-hidden="true"></i>
                            <div class="more_info pl-3">
                                <h6>NEED MORE INFORMATION?</h6>
                                <div>See our <a href="{% url 'dxd:terms-conditions' %}">Returns FAG <div><img src="{% static 'images/clone-icon.png' %}" alt="">
                                        </div></a></div>
                            </div>
                            
                        </div>
                    </div>



                </div>

            </div>


        </section>
    </main>
{% endblock %}